from clases import Particular, Carga, Bicicleta, Motocicleta, Vehiculo, Automovil

particular = Particular("Ford", "Fiesta", 4, "180", "500", 5)
carga = Carga("Daft Trucks", "G 38", 10, 120, "1000", "20000")
bicicleta = Bicicleta("Shimano", "MT Ranger", 2, "Carrera")
motocicleta = Motocicleta("BMW", "F800s", 2, "Deportiva", "2T", "Doble Viga", 21)

print(f"Marca: {particular.marca}", end=", ")
print(f"Modelo: {particular.modelo}", end=", ")
print(f"{particular.n_ruedas} ruedas", end=", ")
print(f"{particular.velocidad} Km/h", end=", ")
print(f"{particular.cilindrada} cc", end=", ")
print(f"Puestos: {particular.n_puestos}")
print(f"Marca: {carga.marca}", end=", ")
print(f"Modelo: {carga.modelo}", end=", ")
print(f"{carga.n_ruedas} ruedas", end=", ")
print(f"{carga.velocidad} Km/h", end=", ")
print(f"{carga.cilindrada} cc", end=", ")
print(f"Carga: {carga.peso_carga} Kg")
print(f"Marca: {bicicleta.marca}", end=", ")
print(f"Modelo: {bicicleta.modelo}", end=", ")
print(f"{bicicleta.n_ruedas} ruedas", end=", ")
print(f"Tipo: {bicicleta.tipo}")
print(f"Marca: {motocicleta.marca}", end=", ")
print(f"Modelo: {motocicleta.modelo}", end=", ")
print(f"{motocicleta.n_ruedas} ruedas", end=", ")
print(f"Tipo: {motocicleta.tipo}", end=", ")
print(f"Motor: {motocicleta.motor}", end=", ")
print(f"Cuadro: {motocicleta.cuadro}", end=", ")
print(f"Nro. Radios: {motocicleta.n_radios}")

print(f"Motocicleta es instancia con relación a Vehículo: {isinstance(motocicleta, Vehiculo)}")
print(f"Motocicleta es instancia con relación a Automóvil: {isinstance(motocicleta, Automovil)}")
print(f"Motocicleta es instancia con relación a Vehículo Particular: {isinstance(motocicleta, Particular)}")
print(f"Motocicleta es instancia con relación a Vehículo de Carga: {isinstance(motocicleta, Carga)}")
print(f"Motocicleta es instancia con relación a Bicicleta: {isinstance(motocicleta, Bicicleta)}")
print(f"Motocicleta es instancia con relación a Motocicleta: {isinstance(motocicleta, Motocicleta)}")
